src/Entity/Issue.php
<?php

namespace App\Entity;

use App\Repository\AuditRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\IssueRepository")
 * @HasLifecycleCallbacks
 */
class Issue
{
    const STATUS_DELETED = 0;
    const STATUS_CREATED = 1;
    const STATUS_IN_PROGRESS = 2;
    const STATUS_CHECK = 3;
    const STATUS_CLOSED = 4;

    public function getStatusName():?string
    {
        $statusNames = [
            self::STATUS_CREATED => "Создана",
            self::STATUS_IN_PROGRESS => "В работе",
            self::STATUS_CHECK => "На проверке",
            self::STATUS_CLOSED => "Закрыта",
        ];

        return $statusNames[$this->status];
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $short_description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $full_description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $result;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="issues")
     * @ORM\JoinColumn(nullable=false)
     */
    private $creator;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="performingIssues")
     */
    private $performer;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Audit", mappedBy="issue")
     */
    private $audits;

    public function __construct()
    {
        $this->audits = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getFullDescription(): ?string
    {
        return $this->full_description;
    }

    public function setFullDescription(?string $full_description): self
    {
        $this->full_description = $full_description;

        return $this;
    }

    public function getResult(): ?string
    {
        return $this->result;
    }

    public function setResult(?string $result): self
    {
        $this->result = $result;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }

    public function setCreateDate(\DateTimeInterface $create_date): self
    {
        $this->create_date = $create_date;

        return $this;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function getPerformer(): ?User
    {
        return $this->performer;
    }

    public function setPerformer(?User $performer): self
    {
        $this->performer = $performer;

        return $this;
    }

    /**
     * @return Collection|Audit[]
     */
    public function getAudits(): Collection
    {
        return $this->audits;
    }

    public function addAudit(Audit $audit): self
    {
        if (!$this->audits->contains($audit)) {
            $this->audits[] = $audit;
            $audit->setIssue($this);
        }

        return $this;
    }

    public function removeAudit(Audit $audit): self
    {
        if ($this->audits->contains($audit)) {
            $this->audits->removeElement($audit);
            // set the owning side to null (unless already changed)
            if ($audit->getIssue() === $this) {
                $audit->setIssue(null);
            }
        }

        return $this;
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     * @param LifecycleEventArgs $event
     */
    public function audit(LifecycleEventArgs $event)
    {
        $entityManager = $event->getEntityManager();
        $unitOfWork = $entityManager->getUnitOfWork();
        $changedFields = $unitOfWork->getEntityChangeSet($this);
        if (array_key_exists('status', $changedFields)) {
            $auditRepository = $entityManager->getRepository(Audit::class);
            $auditRepository->addAuditForIssue($this);
        }
    }


    public function fillNewIssue($creator)
    {
        $this->setStatus(self::STATUS_CREATED);
        $this->setCreator($creator);
        $this->setCreateDate(new \DateTime());
    }

    /**
     * @param User $user
     * @return array
     */
    public function getStatusChoices(User $user)
    {
        $choices = [
            'Created' => 1,
            'In progress' => 2,
        ];
        $roleAdmin = in_array('ROLE_ADMIN', $user->getRoles());
        if ($this->getPerformer() && $this->getPerformer()->getId() == $user->getId() || $roleAdmin) {
            $choices['On check'] = 3;
        }
        if ($roleAdmin) {
            $choices['Closed'] = 4;
        };

        return $choices;
    }

    public function checkResult(FormInterface &$form): bool
    {
        $statusCheck = $this->status == Issue::STATUS_CHECK;
        if ($statusCheck && empty($this->result)) {
            $form
                ->get('result')
                ->addError(new FormError('При передаче на проверку должен быть заполнен результат работы'));
            return false;
        }

        return true;
    }

    /**
     * @param User $user
     * @return bool
     */
    public function takeToWork(User $user): bool
    {
        $issueStatusCreated = $this->getStatus() == Issue::STATUS_CREATED;
        $userNotAdmin = !in_array('ROLE_ADMIN', $user->getRoles());
        if ($issueStatusCreated && $userNotAdmin) {
            $this->setPerformer($user);
            $this->setStatus(Issue::STATUS_IN_PROGRESS);

            return true;
        }

        return false;
    }

}

src/Form/IssueType.php
<?php

namespace App\Form;

use App\Entity\Issue;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IssueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('status')
            ->add('name')
            ->add('short_description')
            ->add('full_description')
            ->add('result')
            ->add('create_date')
            ->add('creator')
            ->add('performer')
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Issue::class,
        ]);
    }
}

src/Controller/IssueController.php
<?php

namespace App\Controller;

use App\Entity\Issue;
use App\Form\IssueEditType;
use App\Form\IssueNewType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class IssueController extends Controller
{
    /**
     * @Route("/", name="homepage", methods="GET")
     */
    public function index(): Response
    {
        $issueTable = $this->getDoctrine()
            ->getRepository('App:Issue')
            ->getIssueTable($this->generateUrl('issues_list_ajax'), $this->getUser()->getId());

        return $this->render('issue/list.html.twig', ['table' => $this->get('kilik_table')->createFormView($issueTable),]);
    }

    /**
     * @Route("/issue/create", name="create-issue", methods="GET|POST")
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $issue = new Issue();
        $form = $this->createForm(IssueNewType::class, $issue);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $issue->fillNewIssue($this->getUser());
            $em = $this->getDoctrine()->getManager();
            $em->persist($issue);
            $em->flush();

            return $this->redirectToRoute('homepage');
        }

        return $this->render('issue/new.html.twig', [
            'issue' => $issue,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/issue/{id}", name="issue_show", methods="GET")
     * @param Issue $issue
     * @return Response
     */
    public function show(Issue $issue): Response
    {
        if ($issue->getStatus() == 0) {
            throw $this->createNotFoundException('Заявка не найдена');
        }

        return $this->render('issue/show.html.twig', [
            'issue' => $issue,
        ]);
    }

    /**
     * @Route("/audit", name="audit", methods="GET")
     */
    public function audit(): Response
    {
        $auditTable = $this->getDoctrine()
            ->getRepository('App:Audit')
            ->getAuditTable($this->generateUrl('audit_list_ajax'));

        return $this->render('audit/list.html.twig', [
            'table' => $this->get('kilik_table')->createFormView($auditTable),
        ]);
    }

    /**
     * @Route("/issue/{id}/edit", name="issue_edit", methods="GET|POST")
     * @param Request $request
     * @param Issue $issue
     * @return Response
     */
    public function edit(Request $request, Issue $issue): Response
    {
        if ($issue->getStatus() == 0) {
            throw $this->createNotFoundException('Заявка не найдена');
        }

        $form = $this->createForm(IssueEditType::class, $issue, ['user' => $this->getUser(),]);
        $issueResult = $issue->getResult();
        $form->handleRequest($request);
        $resultChanged = $issueResult != $issue->getResult();
        if ($form->isSubmitted() && $form->isValid()) {
            $currentUserIsPerformer = $issue->getPerformer() && $issue->getPerformer()->getId() == $this->getUser()->getId();
            $roleAdmin = in_array('ROLE_ADMIN', $this->getUser()->getRoles());
            if (!$currentUserIsPerformer && !$roleAdmin) {
                throw $this->createAccessDeniedException('Вы не являетесь исполнителем данной заявки');
            }
            if ($issue->getStatus() == Issue::STATUS_CLOSED && !$roleAdmin){
                throw $this->createAccessDeniedException('Закрыть задачу может только супервайзер');
            }
            if ($resultChanged && $roleAdmin && !in_array($issue->getStatus(), [Issue::STATUS_CHECK, Issue::STATUS_CLOSED])) {
                throw $this->createAccessDeniedException('Нельзя изменит результат для статусов Создана и В работе');
            }
            if ($issue->checkResult($form)) {
                $this->getDoctrine()->getManager()->flush();

                return $this->redirectToRoute('issue_edit', ['id' => $issue->getId()]);
            }

        }

        return $this->render('issue/edit.html.twig', [
            'issue' => $issue,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/issue/{id}/takeToWork", name="take_to_work", methods="POST")
     * @param Request $request
     * @param Issue $issue
     * @return RedirectResponse
     */
    public function takeToWork(Request $request, Issue $issue): RedirectResponse
    {
        if ($issue->takeToWork($this->getUser())) {
            $this->getDoctrine()->getManager()->flush();
        } else {
            throw $this->createAccessDeniedException("Не возможно взять заявку в работу");
        }

        return $this->redirectToRoute('issue_edit', ['id' => $issue->getId()]);
    }

    /**
     * @Route("/issue/{id}", name="issue_delete", methods="DELETE")
     */
    public function delete(Request $request, Issue $issue): Response
    {
        if ($this->isCsrfTokenValid('delete' . $issue->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $issue->setStatus(Issue::STATUS_DELETED);
            $em->persist($issue);
            $em->flush();
        }

        return $this->redirectToRoute('homepage');
    }

    /**
     * @Route("/list_ajax", name="issues_list_ajax")
     */
    public function _listAction(Request $request)
    {
        $issueTable = $this->getDoctrine()
            ->getRepository('App:Issue')
            ->getIssueTable($this->generateUrl('issues_list_ajax'), $this->getUser()->getId());

        return $this->get('kilik_table')->handleRequest($issueTable, $request);
    }

    /**
     * @Route("/audit_list_ajax", name="audit_list_ajax")
     */
    public function _auditListAction(Request $request)
    {
        $auditTable = $this->getDoctrine()
            ->getRepository('App:Audit')
            ->getAuditTable($this->generateUrl('audit_list_ajax'));

        return $this->get('kilik_table')->handleRequest($auditTable, $request);
    }
}

templates/issue/_delete_form.html.twig
<form method="post" action="{{ path('issue_delete', {'id': issue.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ issue.id) }}">
    <button class="btn">Delete</button>
</form>

templates/issue/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/issue/_list.html.twig
{% extends "@KilikTable/_defaultTable.html.twig" %}
{% block tableBodyStdColumns %}
    <td class="text-right">
        {% if row.object.performer and userId == row.object.performer.id or is_granted('ROLE_ADMIN') %}
            <a href="{{ path('issue_edit', {'id': row.object.id}) }}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        <a href="{{ path('issue_show', {'id': row.object.id}) }}"><span class="glyphicon glyphicon-search"></span></a>
    </td>
    {{ parent() }}
{% endblock tableBodyStdColumns %}

templates/issue/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Система управления заявками - Редактирование заявки{% endblock %}

{% block body %}
    <div>
        <a href="{{ path("homepage") }}"><span class="glyphicon glyphicon-home"></span> Реестр заявок</a>
    </div>

    <h1>Редактирование заявки № {{ issue.id }}</h1>

    {{ include('issue/_form.html.twig') }}

    <div>
        {% if is_granted('ROLE_ADMIN') %}
            {{ include('issue/_delete_form.html.twig') }}
        {% endif %}
    </div>
{% endblock %}

templates/issue/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Issue index{% endblock %}

{% block body %}
    <h1>Issue index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Status</th>
                <th>Name</th>
                <th>Short_description</th>
                <th>Full_description</th>
                <th>Result</th>
                <th>Create_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for issue in issues %}
            <tr>
                <td>{{ issue.id }}</td>
                <td>{{ issue.status }}</td>
                <td>{{ issue.name }}</td>
                <td>{{ issue.short_description }}</td>
                <td>{{ issue.full_description }}</td>
                <td>{{ issue.result }}</td>
                <td>{{ issue.create_date ? issue.create_date|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('issue_show', {'id': issue.id}) }}">show</a>
                    <a href="{{ path('issue_edit', {'id': issue.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('create-issue') }}">Create new</a>
{% endblock %}

templates/issue/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Система управления заявками - Реестр заявок{% endblock %}

{% block body %}

    {% embed "@KilikTable/_defaultTable.html.twig" with {"table": table} %}
        {% block tableTitle %}
            <b>Реестр заявок</b>
            <div class="navbar navbar-right">
                {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path("audit") }}">Журнал изменения статусов</a>&#160;&#160;&#160;
                {% endif %}
                {{ app.user.userfio }} <a href="{{ path("fos_user_security_logout") }}"><span class="glyphicon glyphicon-log-out"></span> Выйти&#160;</a>
            </div>
            <div class="col-lg-12 col-md-6">
                Мои незавершенные заявки
                {{ form_widget(table.formView.i_performer,{"attr": {"class": "refreshOnChange"} }) }}
            </div>
        {% endblock tableTitle %}

        {% block tableHeadStdColumns %}
            <th>
                &nbsp;
            </th>
            {{ parent() }}
        {% endblock tableHeadStdColumns %}

        {% block tableHeadStdFilters %}
            <td>
                &nbsp;
            </td>
            {{ parent() }}
        {% endblock tableHeadStdFilters %}

        {% block tableBodyStdColumns %}
            {% embed "issue/_list.html.twig"%}
            {% endembed %}
        {% endblock tableBodyStdColumns %}
        {% block tableStats %}
            <a href="{{ path("create-issue") }}"><span class="glyphicon glyphicon-plus"></span> Создать заявку </a>
        {% endblock %}
    {% endembed %}

{% endblock body %}


{% block javascript %}
    <script type="text/javascript">
        $(document).ready(function () {
            var table = new KilikTable("{{ table.id }}", "{{ table.path }}");
            table.init();
        });
    </script>

{% endblock javascript %}

templates/issue/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Система управления заявками - Создать заявку{% endblock %}

{% block body %}
    <h1>Создание заявки</h1>

    {{ include('issue/_form.html.twig') }}

    <a href="{{ path('homepage') }}">back to list</a>
{% endblock %}

templates/issue/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Система управления заявками - Просмотр заявки{% endblock %}

{% block body %}
    <div>
        <a href="{{ path("homepage") }}"><span class="glyphicon glyphicon-home"></span> Реестр заявок</a>
    </div>

    <h1>Заявка № {{ issue.id }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th style="min-width: 15em">Название</th>
                <td>{{ issue.name }}</td>
            </tr>
            <tr>
                <th>Исполнитель</th>
                <td>
                    {% if issue.performer %}
                        {{ issue.performer.userfio }}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Создатель</th>
                <td>{{ issue.creator.userfio }}</td>
            </tr>
            <tr>
                <th>Дата создания</th>
                <td>{{ issue.createDate ? issue.createDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Текущий статус</th>
                <td>{{ issue.statusName }}</td>
            </tr>
            <tr>
                <th>Подробное описание</th>
                <td>{{ issue.fullDescription }}</td>
            </tr>
            <tr>
                <th>Результат работы</th>
                <td>{{ issue.result }}</td>
            </tr>
        </tbody>
    </table>

    <div>
        {% if not(is_granted('ROLE_ADMIN')) and issue.status == 1%}
            <form action="{{ path('take_to_work', {'id': issue.id}) }}" method="post">
                <input type="submit" value="Взять заявку в работу">
            </form>
        {% endif %}
    </div>

    {% if is_granted('ROLE_ADMIN') %}
        <div>
            {{ include('issue/_delete_form.html.twig') }}
        </div>
    {% endif %}

{% endblock %}